kind: Secret
apiVersion: v1
metadata:
  name: one-more-secret
type: Opaque
stringData:
  inlineSecret: <path:kv/data/ira_secret#email>
  otherInlineSecret: <path:kv/data/one_more_ira_secret#secret-name>
